name = "ModFest 1.17"
author = "ModFest"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "590d639babb2c94e8ffda1650200f0f41dc00a816be014f44063ad4dc9f84555"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
