name = "ModFest 1.17"
author = "ModFest"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bfbf1e7fdb40bf4a9e02d1760c789a21bc59faf4cc9aaa4d758784b5155d609"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
