name = "ModFest 1.17"
author = "ModFest"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bccb42bc9ca4c4ba5ee755ac1b21d7ba3e8806fe75f68afac625aaab655cab0"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
