name = "ModFest 1.17"
author = "ModFest"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a6b04b9145e766473d13d63e7a697cfa8c8fb41788bbd0303215c1d9bfcb7f4"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
