name = "ModFest 1.17"
author = "ModFest"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d98a80726e536cd51ef70cb38faebd3dfccafb27518e43a28aabcc87f893fe62"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
